Adjust dependencies in the distributable
selsa-inube/inubekit-text pull request #8
Opened 2024-02-15 23:08 UTC by Andresbl123

The **dependencies** of the **distributable** are adjusted, preventing the distributable from containing code that does not strictly belong to the `<Text/> `component.

2024-02-15 23:24 UTC, JanuarAsprilla approved these changes

2024-02-16 02:52 UTC, wfercanas requested changes

2024-02-16 02:52 UTC, wfercanas commented on package.json
>      "@inubekit/foundations": "^1.1.2",
@inubekit/foundations debe estar en dependencies para que cuando se instale inubekit-text, también se instalen las foundations.

2024-02-16 03:17 UTC, Andresbl123 commented on package.json
>      "@inubekit/foundations": "^1.1.2",
resuelto

2024-02-16 04:17 UTC, wfercanas approved these changes

2024-02-16 04:18 UTC, merged