Implement new version of `@inubekit foundations`
selsa-inube/inubekit-text pull request #9
Opened 2024-02-16 20:40 UTC by Andresbl123

New version of the **@inubekit/foundations** library with new color tokens implemented

2024-02-16 20:57 UTC, JanuarAsprilla approved these changes

2024-02-19 17:32 UTC, wfercanas requested changes

2024-02-19 17:32 UTC, wfercanas commented on src/Text/props.ts
>  export type SizeOptions = "large" | "medium" | "small";
Rename to just Size

2024-02-19 17:32 UTC, wfercanas commented on src/Text/props.ts
> +export type TypeOptions = "body" | "display" | "label" | "title" | "headline";
Rename to just Type

2024-02-19 17:32 UTC, wfercanas commented on src/Text/props.ts
>  export type AlignOptions = "start" | "center" | "end" | "justify";
Rename to just Alignment

2024-02-19 17:32 UTC, wfercanas commented on src/Text/props.ts
>  export type HtmlElements =
Rename to HtmlElement

2024-02-19 17:32 UTC, wfercanas commented on src/Text/props.ts
>  export type AlignOptions = "start" | "center" | "end" | "justify";
Refactor to create an array for storing the options and then use that array to create the type:
```js
const aligments = ["start", "center", "end", "justify"] as const;
export type Alignment = typeof aligments[number];
```

With this change, you can now avoid repeating the options in the props structure for storybook.

```js
// Don't ❌
textAlign: {
    options: ["start", "center", "end", "justify"],
    control: { type: "select" },
    description: "This prop controls the text-align style property.",
    table: {
      defaultValue: { summary: "start" },
    },
  },

// Do ✅
textAlign: {
    options: alignments,
    control: { type: "select" },
    description: "This prop controls the text-align style property.",
    table: {
      defaultValue: { summary: "start" },
    },
  },
```

**This change applies to all literal types defined in this file. The array should be in plural (alignments, types, sizes, etc), and the type in singular.**

2024-02-19 21:10 UTC, JanuarAsprilla approved these changes

2024-02-21 02:50 UTC, wfercanas requested changes

2024-02-21 02:50 UTC, wfercanas commented on src/Text/props.ts
> -export type Appearance = keyof typeof inube.color.text;
Create the array `appearances = Object.keys(inube.text)`. With this change:
1. The type can be just keyof typeof appearances 
2. In props, you directly use appearances and not the `Object.keys()` method.

2024-02-21 02:50 UTC, wfercanas commented on src/Text/styles.js
> +  font-family: ${({ theme }) => theme?.font || "Roboto"};
Extend to include a `sans-serif` as fallback.

2024-02-21 17:34 UTC, JanuarAsprilla approved these changes

2024-02-21 20:08 UTC, cmarin001 commented on src/Text/styles.js
> +  font-family: ${({ theme }) => theme?.font || "Roboto"};
solved

2024-02-21 20:12 UTC, cmarin001 commented on src/Text/props.ts
> -export type Appearance = keyof typeof inube.color.text;
solved

2024-02-21 21:30 UTC, JanuarAsprilla approved these changes

2024-02-22 17:13 UTC, wfercanas commented on src/Text/props.ts
> -export type Appearance = keyof typeof inube.color.text;
Si ya creó el array `appearances`, puede usarlo para crear el type Appearance en lugar de volver a ir a `inube.text`. De esta manera todos los types de este estilo quedan con una sola forma de definición.

2024-02-22 17:14 UTC, wfercanas requested changes
Stardardize Appearance type

2024-02-22 17:21 UTC, cmarin001 commented on src/Text/props.ts
> -export type Appearance = keyof typeof inube.color.text;
solved

2024-02-22 19:18 UTC, wfercanas approved these changes

2024-02-22 19:18 UTC, merged